// Glossary tooltip definitions — displayed on hover over dotted-underline terms throughout the UI
export const G = {
  TIC: "Total Installed Cost \u2014 the sum of all bare erected equipment costs plus engineering, CM, and contingencies. Does not include owner's costs.",
  "CAPEX $/t": "Capital intensity \u2014 total capital cost divided by annual CO\u2082 captured. Shows how much upfront investment is needed per tonne of annual capacity. This is NOT an annualized cost. The annualized capital cost (Capital Charge in the LCOC table) applies the CCF (~5\u20138%) to spread this over the project\u2019s economic life.",
  CAPEX: "Capital Expenditure 2014 Total Installed Cost plus owner's costs. Represents the total capital required if built instantaneously.",
  CCF: "Capital Charge Factor \u2014 annualized fraction of CAPEX that must be recovered each year to cover debt service, equity returns, taxes, and depreciation over the project's economic life (typically 30 years).",
  CEPCI: "Chemical Engineering Plant Cost Index \u2014 a widely used index to escalate historical equipment costs to current-year dollars. Published monthly by Chemical Engineering magazine.",
  LCOC: "Levelized Cost of CO\u2082 Captured \u2014 the all-in levelized cost per tonne of CO\u2082 captured, including capital charge, fixed and variable O&M, purchased power, and fuel (if applicable).",
  "Capital Charge": "Annual capital recovery cost per tonne CO\u2082 \u2014 calculated as (CAPEX \u00d7 CCF) / annual CO\u2082 captured. Covers debt payments, equity returns, taxes, depreciation, and insurance on the capital investment.",
  "Fixed O&M": "Fixed Operating & Maintenance costs \u2014 expenses that do not vary with plant output: operating labor, maintenance labor & materials, administrative support, and property taxes/insurance. Expressed in $/t CO\u2082.",
  "Variable O&M": "Variable Operating & Maintenance costs \u2014 expenses that scale with throughput: chemicals and consumables (amine solvent make-up, caustic, desiccant), water treatment, and waste disposal. Expressed in $/t CO\u2082.",
  "Power Cost": "Cost of purchased electricity to run the capture equipment \u2014 compressors, pumps, fans, and auxiliaries. Calculated as (MW demand \u00d7 $/MWh \u00d7 capacity factor \u00d7 8760 hrs) / annual CO\u2082 captured.",
  "Natural Gas Fuel": "Fuel cost for natural gas consumed to generate steam for amine solvent regeneration in post-combustion capture. Scales linearly with gas price. High-purity sources (compression-only) have zero fuel cost.",
  "Location Factor": "State-level construction cost multiplier relative to a Gulf Coast (Louisiana) baseline. Accounts for regional differences in labor rates, productivity, material transport, and regulatory costs.",
  "Capacity Factor": "Fraction of the year the capture plant operates (0\u20131.0). At 85%, the plant runs ~7,446 hours/year. Affects annual CO\u2082 captured and power consumption. For NGCC power plants, equipment is always sized at 100% CF regardless of operating CF.",
  "Six-Tenths Rule": "Empirical cost-scaling law: Cost\u2082 = Cost\u2081 \u00d7 (Capacity\u2082/Capacity\u2081)^0.6. Reflects economies of scale \u2014 doubling capacity increases cost by only ~52%, not 100%.",
  "Scale Adj": "Fixed O&M scale adjustment (exponent n=0.15) \u2014 when capacity changes, fixed costs per tonne decrease modestly due to staffing efficiencies and shared overheads.",
  "Owner's Costs": "Project costs beyond the installed equipment: pre-production/startup, inventory capital, land, financing fees, and other owner expenses. Typically 15\u201325% of Total Installed Cost depending on sector.",
  Retrofit: "Capture equipment added to an existing industrial facility. May include a Retrofit Difficulty Factor (RDF) that increases costs 5\u201315% to account for integration complexity.",
  Greenfield: "A new-build facility where the capture system is designed into the plant from the start. Avoids retrofit difficulty premiums but may include boiler/steam costs.",
  "NETL Ref": "Reference case values from NETL\u2019s \u201cCost of Capturing CO\u2082 from Industrial Sources\u201d (2018 USD, Louisiana Gulf Coast base). All scenarios use post-combustion amine or compression-only technology.",
  "EIA Rate": "U.S. Energy Information Administration (EIA) average industrial electricity price by state, from Table 5.6.a (2024 data). Converted from \u00a2/kWh to $/MWh.",
  "Emission Source": "The industrial process, power plant, or carbon removal system. Point sources have varying CO\u2082 concentrations (~4% NGCC to 99%+ ammonia). CDR sources (DAC, DOC) capture CO\u2082 from ambient air (~420 ppm) or ocean water (~150\u00d7 atmospheric concentration).",
  "Cost Year": "The dollar-year for all cost outputs. CEPCI index is used to escalate from the 2018 NETL base year to the selected year.",
  "Capture Config": "Capture rate (90% or 99%) and build type (Retrofit or Greenfield). Higher capture rates require larger equipment and more energy, increasing costs.",
  "Capture Tech": "Carbon capture technology type. Amine (MEA) is the baseline. Advanced amines reduce energy use. Membranes suit high-purity sources. Solid sorbents are emerging with lower heat requirements. Cryogenic is energy-intensive but yields high-purity CO\u2082.",
  "Project CO\u2082": "Annual tonnes of CO\u2082 captured at the specified capacity factor. This is the denominator in all $/t CO\u2082 calculations.",
  "Power Demand": "Electrical power consumed by the capture system (MW). Includes CO\u2082 compressors, solvent circulation pumps, cooling water pumps, and fans. Scales linearly with CO\u2082 throughput.",
  "Annual Power Cost": "Total electricity expenditure per year = MW \u00d7 $/MWh \u00d7 CF \u00d7 8,760 hours. A major operating cost driver, especially for large industrial/power plant capture.",
  "Total OPEX": "Sum of all annual operating costs per tonne CO\u2082: Fixed O&M + Variable O&M + Power + Fuel. Does not include the capital charge.",
  "Total O&M": "Combined Fixed + Variable O&M costs per tonne CO\u2082, excluding power and fuel. Represents the non-energy operating cost of running the capture plant.",
  "Debt/Equity": "The financing structure assumed by NETL for each sector. Higher equity fractions increase the CCF because equity investors require higher returns than debt holders.",
  "Debt %": "Percentage of project financing from debt (loans/bonds). Higher debt % typically lowers WACC since debt is cheaper than equity, but increases financial risk.",
  "Cost of Debt": "Interest rate on project debt financing. Typically 5-8% for investment-grade projects. Tax-deductible in most jurisdictions (not modeled here).",
  "Cost of Equity": "Required return for equity investors. Typically 10-15% for infrastructure projects, higher for emerging technologies. Reflects risk premium over debt.",
  WACC: "Weighted Average Cost of Capital = (Debt% \u00d7 Cost of Debt) + (Equity% \u00d7 Cost of Equity). The blended cost of financing used to discount future cash flows and calculate the Capital Charge Factor.",
  "Federal Tax": "U.S. federal corporate income tax rate. Current rate is 21% (post-TCJA 2017). Affects after-tax cost of capital and depreciation tax shield value.",
  "State Tax": "State corporate income tax rate. Varies by state (0-12%). Combined with federal tax for total effective tax rate.",
  Depreciation: "Method for recovering capital costs over time for tax purposes. MACRS (Modified Accelerated Cost Recovery System) allows faster depreciation than straight-line, improving project economics through earlier tax shields.",
  "45Q": "Federal tax credit for carbon capture under IRC \u00a745Q (IRA 2022). Pays $85/t CO\u2082 for geologic storage from industrial/power sources, or $180/t for DAC. Credit available for 12 years from placed-in-service date.",
  "48C": "Advanced Energy Project Investment Tax Credit under IRC \u00a748C. Provides 6-30% ITC for qualifying clean energy manufacturing and CCUS projects. Bonus credits available for domestic content and energy communities.",
  LCFS: "California Low Carbon Fuel Standard. Market-based credit system paying ~$50-200/t CO\u2082 for qualifying carbon capture projects that reduce transportation fuel lifecycle emissions. Price varies with market.",
  "CDR Credit": "Carbon Dioxide Removal credits in the Voluntary Carbon Market (VCM). Premium credits for permanent CO\u2082 removal via DAC, BioCCS, enhanced weathering. Current prices: $200-1,000/t depending on permanence, MRV quality, and buyer demand. Major buyers: Microsoft, Stripe, Frontier.",
  "Avoidance Credit": "Emissions avoidance credits in the VCM. Lower-tier credits for preventing CO\u2082 emissions (industrial capture, methane destruction). Prices typically $10-50/t. Subject to additionality and baseline scrutiny. Market softening as buyers shift to removal credits.",
};
